telco_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'target/dev.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: europe-west9
    prod:
      type: duckdb
      path: 'target/prod.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: europe-west9
