telco_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'target/dev.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: eu-west-3
        # GCS configuration
        gcs_region: eu-west-3
        # DuckDB will use GOOGLE_APPLICATION_CREDENTIALS env var for authentication
    prod:
      type: duckdb
      path: 'target/prod.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: eu-west-3
        gcs_region: eu-west-3
